name: Build Docker Images

on:
  push:
    branches:
      - main
  
  watch:
    types: [started]

env:
  DOCKERHUB_REPO: adams549659584/puppeteer-cn-base

jobs:
  buildDockerImage:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}



